### PR TITLE
Support spaces in metadata values

### PR DESCRIPTION
**Pull request by chinedufn**
Example issue:

``` js
var metaString = require('meta-string')

console.log(metaString({content: 'The title'})

// Current result
//=> content=The title

// Result after PR
//=> content="The title"
```

### CODE REVIEW

**Comment by bendrucker** [comment]
When would you have a structured meta value with spaces?

**Comment by chinedufn** [comment]
When creating open graph meta tags:

`<meta property="og:title" content="The Rock" />`

**Comment by bendrucker** [comment]
This lib passes through strings

**Comment by chinedufn** [comment]
I'm not exactly sure what you mean?

If this lib is for generating meta tags why not support spaces in values?

Thanks for clarifying!

**Comment by bendrucker** [comment]
It's not for generating meta tags. It's for generating meta content strings.

**Comment by chinedufn** [comment]
Alright one more point of clarification please:

> A value to transform into the format expected by a `<meta>` tag <- From README

A meta tag expects values to be wrapped in quotation marks if they have spaces, no?

**Comment by bendrucker** [comment]
Nope. That's something else's responsibility.

``` js
h('meta', {name: 'viewport', content: 'width:device-width, initial-scale=1'})
```

**Pull request closed without merging**
